name: Sync Translations with SimpleLocalize

on:
  push:
    branches:
      - master

jobs:
  export-translations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Export translations to SimpleLocalize
        env:
          SIMPLELOCALIZE_PROJECT_TOKEN: 1841797e4f72487fa7cade73b888e4db
        run: |
          curl -H "Authorization: Bearer $SIMPLELOCALIZE_PROJECT_TOKEN" \
               -F "file=@translations.json" \
               https://api.simplelocalize.io/api/v1/translations/upload

  import-translations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Import translations from SimpleLocalize
        env:
          SIMPLELOCALIZE_PROJECT_TOKEN: 1841797e4f72487fa7cade73b888e4db
        run: |
          curl -H "Authorization: Bearer $SIMPLELOCALIZE_PROJECT_TOKEN" \
               -F "file=@translations.json" \
               https://api.simplelocalize.io/api/v1/translations/upload
